### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by alexwilliamlex** [Merrick919/Instagram-posts-to-Discord#2]
hello when you put it on a server you get 
```
2020-11-13T17:26:02.869Z 1536 An error occured.
FetchError: invalid json response body at https://www.instagram.com/accounts/login/?next=/username/%3F__a%3D1 reason: Unexpected token < in JSON at position 0
    at /home/ubuntu/Instagram-posts-to-Discord/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/root/Instagram-posts-to-Discord/main.js:329:24) {
  type: 'invalid-json'
}
```

**Comment by Merrick919** [comment]
Did you make sure that you only put the username for `TARGET_INSTAGRAM_USERNAME` in the .env file? If you are trying to use [this](https://www.instagram.com/username/) account for testing, make sure the `TARGET_INSTAGRAM_USERNAME` value only has the text "username" and not "accounts/login/?next=/username".

**Comment by alexwilliamlex** [comment]
Hello I didn't see your answer :) 
![image](https://user-images.githubusercontent.com/24566508/105106771-ccb69e80-5ab6-11eb-9cc1-6bd65555d9e0.png)
